// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';
import {loadTransfers} from "./transfer";
import {loadPortfolios} from "./portfolio";
import {loadOrders} from "./order";

export const LOADED_USER = 'LOADED_USER';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const ERR_LOGIN = 'ERR_LOGIN';

function loadUserData(dispatch) {
  loadPortfolios()(dispatch);
  loadTransfers()(dispatch);
  loadOrders()(dispatch);
}

export function loadUser() {
  return dispatch => {
    const succCb = ({ username }) => {
      loadUserData(dispatch)
      dispatch({ type: LOADED_USER, username })
    }
    const errCb = () => dispatch({ type: LOADED_USER, username: null })
    return coattails.post("/auth/user", {}, succCb, errCb)
  }
}

export function login(username: string, password: string) {
  return dispatch => {
    dispatch({ type: LOGGING_IN });
    let body = JSON.stringify({username, password});
    const succCb = () => {
      loadUserData(dispatch)
      dispatch({ type: LOADED_USER, username })
    }
    const errCb = e => {
      if (e === 401) {
        dispatch({ type: ERR_LOGIN, msg: "Invalid login credentials" })
      } else {
        dispatch({ type: ERR_LOGIN, msg: "Unknown error in logging in. Status code: " + e })
      }
    }
    return coattails.post("/auth/login", { body }, succCb, errCb)
  }
}

export function logout() {
  return dispatch => {
    const succCb = () => dispatch({ type: LOGGED_OUT })
    return coattails.post("/auth/logout", {}, succCb)
  }
}
