// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';

export const SEARCHING_QUOTE = 'SEARCHING_QUOTE';
export const SEARCHED_QUOTE = 'SEARCHED_QUOTE';

export function searchQuote(stock) {
  return dispatch => {
    dispatch({ type: SEARCHING_QUOTE})
    const succCb = quotes => dispatch({ type: SEARCHED_QUOTE, payload: quotes})
    return coattails.get("/auth/positions", {}, succCb)
  }
}
