// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';

export const LOADING_PORTS = 'LOADING_PORTS';
export const LOADED_PORTS = 'LOADED_PORTS';

export function loadPortfolios() {
  return dispatch => {
    dispatch({ type: LOADING_PORTS })
    const succCb = portfolios => dispatch({ type: LOADED_PORTS, portfolios })
    return coattails.get("/auth/portfolio", {}, succCb)
  }
}

