// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';

export const LOADING_PORTS = 'LOADING_PORTS';
export const LOADED_PORTS = 'LOADED_PORTS';
export const SELECT_PORT = 'SELECT_PORT';
export const ADDING_PORT = 'ADDING_PORT';
export const ADDED_PORT = 'ADDED_PORT';
export const ERR_ADDING_PORT = 'ERR_ADDING_PORT';
export const RESET_REDIRECT = 'RESET_REDIRECT;'
export const LOADING_PORT_HISTORIES = 'LOADING_PORT_HISTORIES';
export const LOADED_PORT_HISTORIES = 'LOADED_PORT_HISTORIES';

export function loadPortfolios() {
  return dispatch => {
    dispatch({ type: LOADING_PORTS })
    const succCb = portfolios => dispatch({ type: LOADED_PORTS, portfolios })
    return coattails.get("/auth/portfolio", {}, succCb)
  }
}

export function resetRedirect() {
  return dispatch => {
    dispatch({ type: RESET_REDIRECT })
  }
}

export function selectPort(id) {
  return dispatch => {
    dispatch({ type: SELECT_PORT, id })
  }
}

export function addPortfolio(name, type, tdCode, tdAccNum) {
  return dispatch => {
    dispatch({type: ADDING_PORT})
    if (type==='tda') {
      let body = JSON.stringify({name, code: tdCode, account_num: tdAccNum})
      const succCb = portfolios => dispatch({ type: ADDED_PORT, portfolios })
      return coattails.post("/auth/tda/portfolio/create", {body}, succCb)
    } else {
      let body = JSON.stringify({name, type});
      const succCb = portfolios => dispatch({ type: ADDED_PORT, portfolios })
      const errCb = e => {
        console.log("ERR", e)
        dispatch({ type: ERR_ADDING_PORT, error: e })
      }
      return coattails.post("/auth/portfolio/create", {body}, succCb, errCb)
    }
  }
}

export function loadPortHistories() {
  return dispatch => {
    dispatch({ type: LOADING_PORT_HISTORIES })
    const succCb = histories => dispatch({ type: LOADED_PORT_HISTORIES, payload: histories })
    return coattails.get("/auth/portfolio/history", {}, succCb)
  }
}