// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';

export const LOADING_POSITIONS = 'LOADING_POSITIONS';
export const LOADED_POSITIONS = 'LOADED_POSITIONS';

export function loadPositions() {
  return dispatch => {
    dispatch({ type: LOADING_POSITIONS})
    const succCb = positions => dispatch({ type: LOADED_POSITIONS, payload: positions})
    return coattails.get("/auth/positions", {}, succCb)
  }
}
