// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';

export const LOADING_TD_ACCOUNTS = 'LOADING_TD_ACCOUNTS';
export const LOADED_TD_ACCOUNTS = 'LOADED_TD_ACCOUNTS';

export function loadAccounts() {
  return dispatch => {
    dispatch({ type: LOADING_TD_ACCOUNTS })
    const succCb = accounts => dispatch({ type: LOADED_TD_ACCOUNTS, accounts })
    return coattails.get("/auth/tda", {}, succCb)
  }
}

// export function resetRedirect() {
//   return dispatch => {
//     dispatch({ type: RESET_REDIRECT })
//   }
// }
//
// export function selectPort(id) {
//   return dispatch => {
//     dispatch({ type: SELECT_PORT, id })
//   }
// }
//
// export function addBrokerage(name, type) {
//   return dispatch => {
//     dispatch({type: ADDING_PORT})
//     let body = JSON.stringify({name, type});
//     const succCb = brokerage => dispatch({ type: ADDED_PORT, brokerage })
//     const errCb = e => dispatch({ type: ERR_ADDING_PORT, error: e })
//     return coattails.post("/auth/brokerage/create", {body}, succCb, errCb)
//   }
// }