// Example action file. Generated by gen_component
import * as coattails from '../util/coattails';
import { getUid } from "./helpers";

export const LOADING_TRANSFERS = 'LOADING_TRANSFERS';
export const LOADED_TRANSFERS = 'LOADED_TRANSFERS';
export const UPSERTING_TRANSFER = 'UPSERTING_TRANSFER';
export const UPSERTED_TRANSFER = 'UPSERTED_TRANSFER';
export const ERR_UPSERTING_TRANSFER = 'ERR_ADDING_TRANSFER';

export function loadTransfers() {
  return dispatch => {
    dispatch({ type: LOADING_TRANSFERS})
    const succCb = transfers => dispatch({ type: LOADED_TRANSFERS, transfers })
    return coattails.get("/auth/transfer", {}, succCb)
  }
}

interface TransferRequest {
  uid?: string;
  port_id: number;
  amount: number;
  is_deposit: boolean;
  manually_added: boolean;
  date: Date;
}

export function upsertTransfer(transfer: TransferRequest) {
  return dispatch => {
    dispatch({type: UPSERTING_TRANSFER})
    let body = JSON.stringify({
      uid: transfer.uid ? transfer.uid : getUid(),
      port_id: transfer.port_id,
      amount: transfer.amount,
      is_deposit: transfer.is_deposit,
      manually_added: transfer.manually_added,
      date: transfer.date,
    });
    const succCb = transfers => dispatch({ type: UPSERTED_TRANSFER, transfers })
    const errCb = e => dispatch({ type: ERR_UPSERTING_TRANSFER, error: e })
    return coattails.post("/auth/transfer/upsert", {body}, succCb, errCb)
  }
}

export function deleteTransfer(uid: string) {
  return dispatch => {
    dispatch({type: UPSERTING_TRANSFER})
    let body = JSON.stringify({ uid })
    const succCb = transfers => dispatch({ type: UPSERTED_TRANSFER, transfers })
    return coattails.post("/auth/transfer/delete", {body}, succCb)
  }
}