// Example action file. Generated by gen_component
export const LOADED_USER = 'LOADED_USER';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_OUT = 'LOGGED_OUT';

export function loadUser() {
  return dispatch => {
    const succCb = ({ username }) => dispatch({ type: LOADED_USER, username })
    return fetchCoattails.post("/auth/user", {}, succCb)
  }
}

export function login(username: string, password: string) {
  return dispatch => {
    dispatch({ type: LOGGING_IN });
    let body = JSON.stringify({username, password});
    const succCb = () => dispatch({ type: LOADED_USER, username })
    return fetchCoattails.post("/auth/login", { body }, succCb)
  }
}

export function logout() {
  return dispatch => {
    const succCb = () => dispatch({ type: LOGGED_OUT })
    return fetchCoattails.post("/auth/logout", {}, succCb)
  }
}
