// Example action file. Generated by gen_component
export const LOADED_USER = 'LOADED_USER';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER = 'REGISTER';
export const LOGGED_OUT = 'LOGGED_OUT';

export function loadUser() {
  return dispatch => {
    let headers = {
      "Content-Type": "application/json",
    };
    return fetch("http://127.0.0.1:8080/auth/user", { headers, method: "POST", credentials: 'include' })
      .then(res => {
        if (res.ok) {
          return res.json()
        }
        throw Error("unauthorized user")
      })
      .then(({ username })=> {
        dispatch({ type: LOADED_USER, username })
      })
      .catch(e => {
        console.error(e);
      });
  }
}

export function login(username: string, password: string) {
  return dispatch => {
    dispatch({ type: LOGGING_IN });
    let body = JSON.stringify({username, password});
    let headers = {
      "Content-Type": "application/json",
    };
    return fetch("http://127.0.0.1:8080/auth/login", { body, headers, method: "POST", credentials: 'include', })
      .then(res => {
        if (res.ok) {
          dispatch({ type: LOADED_USER, username })
        }
      })
  }
}

export function logout() {
  return dispatch => {
    let headers = {
      "Content-Type": "application/json",
    };
    return fetch("http://127.0.0.1:8080/auth/logout", { headers, method: "POST", credentials: 'include' })
      .then(res => {
        dispatch({ type: LOGGED_OUT })
      })
  }
}
