// Example reducer file. Generated by gen_component
import {
  ERR_LOGIN,
  LOADED_USER,
  LOGGED_OUT,
  ERR_REGISTERING,
} from "../actions/auth";

const initialState = {
  username: "",
  err_login_msg: "",
}

export default function auth(state=initialState, action) {
  switch (action.type) {
    case ERR_REGISTERING:
    case ERR_LOGIN:
      return {...state, err_login_msg: action.msg }
    case LOADED_USER:
      return {...state, username: action.username, err_login_msg: "" }
    case LOGGED_OUT:
      return Object.assign(initialState, { username: null })
    default:
      return state
  }
}