// Example reducer file. Generated by gen_component
import {
  ADDED_PORT,
  ADDING_PORT,
  ERR_ADDING_PORT,
  LOADING_PORTS,
  LOADED_PORTS,
  SELECT_PORT,
  RESET_REDIRECT,
} from "../actions/portfolio";
import {LOGGED_OUT} from "../actions/auth";

const initialState = {
  portfolios : [] as any[],
  loading: false,
  selected_port: -1,
  adding_port: false,
  err_adding_port: false,
  redirect: false,
}

export default function portfolio(state=initialState, action) {
  switch (action.type) {
    case ADDED_PORT:
      // NOTE(ma): this is kinda hacky, but we basically assume the latest portfolio added is at the end :D
      // this is due to our auto incrementing id backend
      return {...state, adding_port: false, portfolios: action.portfolios, selected_port: action.portfolios[action.portfolios.length-1].id, redirect: true}
    case ADDING_PORT:
      return {...state, adding_port: true}
    case ERR_ADDING_PORT:
      return {...state, adding_port: false, err_adding_port: true}
    case LOADING_PORTS:
      return {...state, loading: true }
    case LOADED_PORTS:
      return {...state, loading: false, portfolios: action.portfolios}
    case RESET_REDIRECT:
      return {...state, redirect: false}
    case SELECT_PORT:
      return {...state, selected_port: action.id }
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}