// Example reducer file. Generated by gen_component
import { LOADING_PORTS, LOADED_PORTS } from "../actions/portfolio";

const initialState = {
  portfolios: [],
  loading: false,
}

export default function portfolio(state=initialState, action) {
  switch (action.type) {
    case LOADING_PORTS:
      return {...state, loading: true }
    case LOADED_PORTS:
      return {...state, loading: false, portfolios: action.portfolios}
    default:
      return state
  }
}