// Example reducer file. Generated by gen_component
import {
  ADDED_PORT,
  ADDING_PORT,
  ERR_ADDING_PORT,
  LOADING_PORTS,
  LOADED_PORTS,
  SELECT_PORT,
  RESET_REDIRECT,
  LOADED_PORT_HISTORIES,
  LOADED_PORT_COMPARISON,
  RELOAD_CURRENT_PORT_VALUES,
  RELOAD_DAILY_PORT_VALUES,
} from "../actions/portfolio";
import {LOGGED_OUT} from "../actions/auth";

const initialState = {
  portfolios : [] as any[],
  loading: false,
  selected_port: -1,
  adding_port: false,
  err_adding_port: false,
  redirect: false,
  port_histories: {},
  comparison: [],
  port_values: {},
  daily_port_values: {},
}

export default function portfolio(state=initialState, action) {
  switch (action.type) {
    case ADDED_PORT:
      // NOTE(ma): this is kinda hacky, but we basically assume the latest portfolio added is at the end :D
      // this is due to our auto incrementing id backend
      return {...state, adding_port: false, portfolios: action.portfolios, selected_port: action.portfolios[action.portfolios.length-1].id, redirect: true}
    case ADDING_PORT:
      return {...state, adding_port: true}
    case ERR_ADDING_PORT:
      return {...state, adding_port: false, err_adding_port: true}
    case LOADING_PORTS:
      return {...state, loading: true }
    case LOADED_PORTS:
      return {...state, loading: false, portfolios: action.portfolios}
    case RELOAD_CURRENT_PORT_VALUES:
      Object.keys(action.payload).forEach(k => {
        state = {...state, port_values: { ...state.port_values, [k]: action.payload[k] }}
      })
      return state
    case LOADED_PORT_HISTORIES:
      return {...state, port_histories: action.payload }
    case LOADED_PORT_COMPARISON:
      return {...state, comparison: action.comparison}
    case RELOAD_DAILY_PORT_VALUES:
      return {...state, daily_port_values: action.payload}
    case RESET_REDIRECT:
      return {...state, redirect: false}
    case SELECT_PORT:
      return {...state, selected_port: action.id }
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}