// Example reducer file. Generated by gen_component
import {
  LOADING_POSITIONS,
  LOADED_POSITIONS
} from "../actions/position";

import {
  LOGGED_OUT
} from "../actions/auth";

const initialState = {
  positions: [] as any[],
  loading: false,
}

export default function order(state=initialState, action) {
  switch (action.type) {
    case LOADING_POSITIONS:
      return {...state, loading: true}
    case LOADED_POSITIONS:
      return {...state, loading: false, positions: action.payload }
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}