// Example reducer file. Generated by gen_component
import {
  CONNECTED,
  CONNECTING
} from "../actions/sock";
import {LOGGED_OUT} from "../actions/auth";

const initialState = {
  connecting: false,
  connected: false,
}

export default function sock(state=initialState, action) {
  switch (action.type) {
    case CONNECTING:
      return {...state, connecting: true }
    case CONNECTED:
      return {...state, connected: true, connecting: false }
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}