// Example reducer file. Generated by gen_component
import {
  LOADED_TD_ACCOUNTS,
  LOADING_TD_ACCOUNTS,
} from "../actions/tda";
import {LOGGED_OUT} from "../actions/auth";

const initialState = {
  accounts: [] as any[],
  loading: false,
  // adding_brokerage: false,
  // err_adding_brokerage: false,
}

export default function tda(state=initialState, action) {
  switch (action.type) {
    case LOADED_TD_ACCOUNTS:
      return {...state, loading: false, accounts: action.accounts}
    case LOADING_TD_ACCOUNTS:
      return {...state, loading: true}
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}