// Example reducer file. Generated by gen_component
import { ERR_LOGIN, LOADED_USER, LOGGED_OUT } from "../actions/auth";

const initialState = {
  username: null,
  err_login_msg: "",
}

export default function auth(state=initialState, action) {
  switch (action.type) {
    case ERR_LOGIN:
      return {...state, err_login_msg: action.msg }
    case LOADED_USER:
      return {...state, username: action.username, err_login_msg: "" }
    case LOGGED_OUT:
      return initialState
    default:
      return state
  }
}