// Example reducer file. Generated by gen_component
import {LOADED_USER, LOGGED_OUT } from "../actions/auth";

const initialState = {
  username: null
}

export default function auth(state=initialState, action) {
  switch (action.type) {
    case LOADED_USER:
      return {...state, username: action.username }
    case LOGGED_OUT:
      return {...state, username: null}
    default:
      return state
  }
}